# ====================================================
# カメラ設定（必要な場合）
# ====================================================
[camera]
position = [55.0, 40.0, 295.6]
direction = [0.0, -0.12, -1.0]
width = 640
height = 480
samples = 16
plane_distance = 70.0

# ====================================================
# オブジェクト一覧 
# ====================================================
[[objects]]
name = "cornelbox"
type = "bvh_obj"
filename = "cornelbox.obj"

[[objects]]
name = "cornelbox"
type = "obj"
filename = "model.obj"
